### ISSUE TITLE
How to stop the web service by a function call?

### ISSUE THREAD

**Issue by stefansavev-o** [micro/go-web#11]
In go-micro/server/server.go, function Run, I find this code to stop the server:

	ch := make(chan os.Signal, 1)
	signal.Notify(ch, syscall.SIGTERM, syscall.SIGINT, syscall.SIGKILL)
	log.Logf("Received signal %s", <-ch)
This code relies on syscall.SIGTERM and might interact with other parts of the application.
Is it possible to expose a Stop function, which will send to the channel directly.
In the short run we are looking for a very simple fix.
For example a new run function with a signature:

RunWithStopChannel(ch <-channel)
where we have access to the channel will do for us.

**Comment by asim** [comment]
There is currently no supported method for this. We'd likely use the same pattern as go-micro which would allow Context to be specified and used for signalling cancellation. Feel free to PR it.

**Comment by asim** [comment]
Go-web has been updated to take a Context option which can cancel/shutdown the service.

In this example we shutdown the service after 5 seconds. Hopefully this satisfies the request.

```
package main

import (
	"context"
	"time"

	"github.com/micro/go-web"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())

	go func() {
		<-time.After(time.Second * 5)
		cancel()
	}()

	w := web.NewService(
		web.Context(ctx),
	)

	w.Run()
}
```

**Comment by stefansavev-o** [comment]
Oh, wow! Awesome.
