### ISSUE TITLE
If the service name contains an underscore, the browser path will not be found

### ISSUE THREAD

**Issue by locxiang** [micro/go-web#18]
![image](https://user-images.githubusercontent.com/6622033/41448120-62b3dc68-708b-11e8-8b03-6397e14f17c8.png)

![image](https://user-images.githubusercontent.com/6622033/41448124-66e4020e-708b-11e8-8045-5d3d4bccb31c.png)

![image](https://user-images.githubusercontent.com/6622033/41448126-6a539012-708b-11e8-8d49-c9483747adff.png)

```shell
micro --registry_address=consul:8500 --register_interval=5 --register_ttl=10 --enable_stats web --namespace=go.micro.web
```

**Comment by asim** [comment]
Fixed. Now supports hyphens in service name.
