### ISSUE TITLE
flag redefined: register_ttl

### ISSUE THREAD

**Issue by drichner** [micro/go-web#20]
When I run the example I get this error:

flag redefined: register_ttl
panic: flag redefined: register_ttl

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420074360, 0x9d0ba0, 0xc4200268c8, 0x9763b2, 0xc, 0x97b885, 0x17)
	/usr/local/go/src/flag/flag.go:810 +0x540
flag.(*FlagSet).IntVar(0xc420074360, 0xc4200268c8, 0x9763b2, 0xc, 0x0, 0x97b885, 0x17)
	/usr/local/go/src/flag/flag.go:609 +0x71
flag.(*FlagSet).Int(0xc420074360, 0x9763b2, 0xc, 0x0, 0x97b885, 0x17, 0xc)
	/usr/local/go/src/flag/flag.go:622 +0x77
github.com/micro/cli.IntFlag.Apply.func1(0x9763b2, 0xc)
	/home/drichner/goprojs/src/github.com/micro/cli/flag.go:417 +0xad
github.com/micro/cli.eachName(0x9763b2, 0xc, 0xc4200655c0)
	/home/drichner/goprojs/src/github.com/micro/cli/flag.go:55 +0xb2
github.com/micro/cli.IntFlag.Apply(0x9763b2, 0xc, 0x0, 0x97b885, 0x17, 0x978a71, 0x12, 0x0, 0xc420074360)
	/home/drichner/goprojs/src/github.com/micro/cli/flag.go:412 +0x1a2
github.com/micro/cli.flagSet(0x0, 0x0, 0xc4200d0840, 0x18, 0x2c, 0xc42009d320)
	/home/drichner/goprojs/src/github.com/micro/cli/flag.go:46 +0x75
github.com/micro/cli.(*App).Run(0xc4200cc6e0, 0xc42001e1b0, 0x1, 0x1, 0x0, 0x0)
	/home/drichner/goprojs/src/github.com/micro/cli/app.go:134 +0x69c
github.com/micro/cli.(*App).RunAndExitOnError(0xc4200cc6e0)
	/home/drichner/goprojs/src/github.com/micro/cli/app.go:208 +0x53
github.com/micro/go-micro/cmd.(*cmd).Init(0xc4200c2420, 0x0, 0x0, 0x0, 0x17, 0xc4200d0840)
	/home/drichner/goprojs/src/github.com/micro/go-micro/cmd/cmd.go:433 +0xf1
github.com/micro/go-web.(*service).Init(0xc42009d0e0, 0x0, 0x0, 0x0, 0xc42009d0e0, 0x0)
	/home/drichner/goprojs/src/github.com/micro/go-web/service.go:282 +0x2e2
main.main()
	/home/drichner/goprojs/src/github.com/micro/go-web/examples/helloworld/helloworld.go:22 +0xd1

**Comment by asim** [comment]
You likely have out of date source code. go get - u and then close this issue if fixed.

**Comment by drichner** [comment]
I did not go get -u ;-)
just realized it after I wrote the issue...
