### ISSUE TITLE
satisfy micro.Service interface

### ISSUE THREAD

**Issue by vtolstov** [micro/go-web#23]
I'm try to register all services in single place with memory register, also init and run.
(i have single binary app combined multiple services) now as i see go-web does not provide the same interface as needed (micro.Service)

**Comment by asim** [comment]
Go Web serves a different purpose to Go Micro. Please don't use it if you're looking for a go-micro interface.

**Comment by vtolstov** [comment]
@asim why? i need to provide rest endpoint, as i understand i need to use go-web for this

**Comment by asim** [comment]
You can use anything you want to provide a rest endpoint. Go web is not compulsory. It's just a convenience mechanism for registering a web based service. 

Right now there's no plans for the micro.Service interface but maybe we'll look into it in the future. We want the interface to be useful for web development first and foremost. Likely some form of wasm integration.

**Comment by vtolstov** [comment]
ok, thanks. If i need to provide to external clients only grpc and rest endpoints (something like api gateway) for grpc i can use go-grpc from micro. does micro provide some stuff for rest, or i need to use grpc-gateway for example?
