### ISSUE TITLE
Graceful stop

### ISSUE THREAD

**Issue by vyacheslavk** [micro/go-web#7]
is it possible to gracefully stop web service? Or need to implement own os.Signal listener?
```go
service := web.NewService(
		web.Name("go.micro.api.service")
)
```
because its not accept BeforeStop options

**Comment by asim** [comment]
A service created with the go-web library gracefully exits. It waits for a kill signal. See here https://github.com/micro/go-web/blob/master/service.go#L276L277. Other operations are not guaranteed to be graceful.

**Comment by vyacheslavk** [comment]
Yes i find out that micro have BeforeStop and AfterStop callbacks and they working like i need it, but why not todo same functionality for web services?

**Comment by asim** [comment]
If you want the functionality of go-micro then look at the http server plugin https://github.com/micro/go-plugins/tree/master/server/http

**Comment by asim** [comment]
Closing the issue. Please use the http server plugin as stated above if you would like the extra functionality.
